"""
AegisLog Event Models

Defines the structured data models used throughout AegisLog.
"""

from dataclasses import dataclass


@dataclass
class AuthEvent:
    """Represents a normalized SSH authentication event."""

    timestamp: str
    hostname: str
    service: str
    pid: int
    status: str
    username: str
    source_ip: str
    source_port: int
    protocol: str
    invalid_user: bool
    raw_log: str

@dataclass
class ThreatFinding:
    """Represents a security finding generated by the detection engine."""

    attack_type: str
    severity: str
    source_ip: str
    target_user: str
    attempts: int
    service: str
    first_seen: str
    last_seen: str
    recommendation: str

