"""
AegisLog Windows Real-Time Security Monitor

Reads new Windows Security Event Log authentication events,
normalizes them into AuthEvent objects, and sends them through
the existing AegisLog LiveDetector.
"""

import time

import win32evtlog

from live_detector import LiveDetector
from windows_parser import parse_windows_event


SECURITY_LOG = "Security"

SUCCESSFUL_LOGON = 4624
FAILED_LOGON = 4625


def get_latest_record_number(handle):
    """Get the newest Windows Security Event record number."""

    events = win32evtlog.ReadEventLog(
        handle,
        win32evtlog.EVENTLOG_BACKWARDS_READ
        | win32evtlog.EVENTLOG_SEQUENTIAL_READ,
        0,
    )

    if not events:
        return 0

    return events[0].RecordNumber


def print_finding(finding):
    """Display a security finding generated by LiveDetector."""

    print("")
    print("!" * 50)
    print("        AEGISLOG SECURITY ALERT")
    print("!" * 50)

    print(f"Attack Type : {finding.attack_type}")
    print(f"Severity    : {finding.severity}")
    print(f"Source IP   : {finding.source_ip}")
    print(f"Target User : {finding.target_user}")
    print(f"Attempts    : {finding.attempts}")

    ip_classification = getattr(
        finding,
        "ip_classification",
        None,
    )

    if ip_classification:
        print(f"IP Type     : {ip_classification}")

    print(f"First Seen  : {finding.first_seen}")
    print(f"Last Seen   : {finding.last_seen}")

    print("Recommendation")
    print(finding.recommendation)

    print("!" * 50)
    print("")


def monitor_windows_log(poll_interval=1):
    """Monitor Windows Security events in real time."""

    try:
        handle = win32evtlog.OpenEventLog(
            None,
            SECURITY_LOG,
        )

    except Exception as error:
        print(
            f"ERROR: Unable to open Security log: {error}"
        )
        return

    detector = LiveDetector()

    last_record_number = get_latest_record_number(handle)

    print("=" * 60)
    print("          AEGISLOG WINDOWS LIVE MONITOR")
    print("=" * 60)
    print(f"Log        : {SECURITY_LOG}")
    print("Status     : ACTIVE")
    print("Events     : 4624, 4625")
    print("Detection  : ENABLED")
    print("Press Ctrl+C to stop.")
    print("=" * 60)
    print("")
    print(
        f"Starting after event record: "
        f"{last_record_number}"
    )
    print("")
    print("Waiting for NEW authentication events...")
    print("")

    try:

        while True:

            events = win32evtlog.ReadEventLog(
                handle,
                win32evtlog.EVENTLOG_FORWARDS_READ
                | win32evtlog.EVENTLOG_SEQUENTIAL_READ,
                0,
            )

            if not events:
                time.sleep(poll_interval)
                continue

            for event in events:

                record_number = event.RecordNumber

                if record_number <= last_record_number:
                    continue

                last_record_number = record_number

                event_id = event.EventID & 0xFFFF

                if event_id not in (
                    SUCCESSFUL_LOGON,
                    FAILED_LOGON,
                ):
                    continue

                auth_event = parse_windows_event(event)

                if auth_event is None:
                    continue

                print("")
                print("-" * 60)

                if auth_event.status == "FAILED":
                    print("WINDOWS FAILED AUTHENTICATION")
                else:
                    print("WINDOWS SUCCESSFUL AUTHENTICATION")

                print("-" * 60)
                print(f"Username    : {auth_event.username}")
                print(f"Source IP   : {auth_event.source_ip}")
                print(f"Status      : {auth_event.status}")
                print(f"Event ID    : {event_id}")
                print(f"Record      : {record_number}")
                print("-" * 60)

                findings = detector.add_event(auth_event)

                for finding in findings:
                    print_finding(finding)

            time.sleep(poll_interval)

    except KeyboardInterrupt:

        print("")
        print("AegisLog Windows monitor stopped.")

    except Exception as error:

        print("")
        print(
            f"ERROR: Windows monitor failed: {error}"
        )

    finally:
        win32evtlog.CloseEventLog(handle)


if __name__ == "__main__":
    monitor_windows_log()